# Numpy is the core for pandas. Pandas is build on top of Numpy in order to provide a higher level of access to the powerfull math operations. 


In [1]:
import pandas as pd
import numpy as np

In [2]:
# read in the csv file aka dataframe creation

url_data = "https://raw.githubusercontent.com/sb0709/bootcamp_KSU/master/Data/data.csv"
data = pd.read_csv(url_data,sep=',')

# convert the pandas dataframe to numpy array . 

``` python
    DataFrame.values
    ```
   
* Return a Numpy representation of the DataFrame.

* Only the values in the DataFrame will be returned, the axes labels will be removed.

```python
Returns:	
        numpy.ndarray
        The values of the DataFrame.
```





http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.values.html#pandas.DataFrame.values


In [3]:
data.dtypes

Unnamed: 0     int64
MATCHKEY       int64
RBAL           int64
TRADES         int64
AGE            int64
AGE_groups    object
DELQID         int64
CRELIM         int64
goodbad        int64
BRNEW          int64
BRAGE          int64
dtype: object

In [4]:
# get numpy array with buildin function ".values"

np_data = data.values

In [5]:
# Type of the 

type(np_data)

numpy.ndarray

In [6]:
# slice the matrices, row slice

np_data[0,:]

array([0, 16345246, 1492, 4, 39, 'AG_30_50', 1, 750, 0, 5, 20],
      dtype=object)

In [7]:
# column slice, and this also can be passed to a variables, 
# numpy anytime is made a change to a numpy array is replacing the original one, for example recreating the A than modify some variable will recreate a NEW A matrix in place. 


np_data[:,1:5]

array([[16345246, 1492, 4, 39],
       [13728016, 0, 3, 71],
       [14716776, 854, 9, 30],
       ...,
       [14552548, 24043, 34, 47],
       [3267611, 18108, 30, 58],
       [3380958, 10793, 29, 67]], dtype=object)

Sources used to build the tutorial:

* A Primer on Scientific Programming with Python by Hans Petter Langtangen.
* Deep Learning by Ian Goodfellow, Yoshua Bengio, and Aaron Courville.
* https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
* https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/
* https://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.ndarray.html



##### This part does assume that the audience have previous experience with basic Linear Algebra, including Vectors, Matrices, Tensors.

### Scalars
##### The default data type in NumPy is float_

Source doc: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html 

In [8]:
#listing the 

np.ScalarType

(int,
 float,
 complex,
 int,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.int8,
 numpy.uint8,
 numpy.int16,
 numpy.uint16,
 numpy.int32,
 numpy.uint32,
 numpy.int64,
 numpy.uint64,
 numpy.int64,
 numpy.uint64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float128,
 numpy.complex64,
 numpy.complex128,
 numpy.complex256,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.void,
 numpy.datetime64,
 numpy.timedelta64)

In [9]:
a = np.array(3.1)

In [10]:
a

array(3.1)

In [11]:
b = np.array(3, dtype=float)

In [12]:
b

array(3.)

# Defining Matrics and Vectors

##### A matrix  is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns:
![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Matrix.svg/494px-Matrix.svg.png?raw=true)

https://www.wikiwand.com/en/Matrix_(mathematics)

In [81]:
# Define matrix "A"

A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(A)
print()
print("Shape of the matrix is:", A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of the matrix is: (3, 3)


### Addition, scalar multiplication and transposition

![alt text](https://github.com/sb0709/bootcamp_KSU/blob/master/pictures/matrix_table.png?raw=true)


https://www.wikiwand.com/en/Matrix_(mathematics)

In [82]:
B = A**2
print(B)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [83]:
# we can add matrices to each other, as long as they have the same shape, just by adding their corresponding elements: C = A + B

C = A + B
print(C)

[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


In [84]:
# scalar multiply matrix, is performed by multiply each element of a matrix to a scalar

D = 2 * C
D

array([[  4,  12,  24],
       [ 40,  60,  84],
       [112, 144, 180]])

In [85]:
# scalar addition to matrix, is performed by adding each element of a matrix to a scalar

E = 2 + C
E

array([[ 4,  8, 14],
       [22, 32, 44],
       [58, 74, 92]])

In [86]:
# Transpose 
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [87]:
# inverse

print(np.linalg.inv(E))

# here we have also the Generalized inverse option to can calculate.

[[ 1.44444444 -1.38888889  0.44444444]
 [-2.44444444  2.05555556 -0.61111111]
 [ 1.05555556 -0.77777778  0.22222222]]


# How to find determinant of a matrix

![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/5b2e40d390e1d26039aabee44c7d1d86c8755232?raw=true)

Source info: https://www.wikiwand.com/en/Determinant

In [88]:
# Determinant


print(np.linalg.det(A))

6.66133814775094e-16


# Eigenvalue and eigenvectors


Source: https://www.wikiwand.com/en/Eigenvalues_and_eigenvectors 
http://mathworld.wolfram.com/Eigenvalue.html

In [89]:
# Eigenvalues and Eigenvectors

eigvals, eigvecs = np.linalg.eig(A)

print(eigvals)
print()
print(eigvecs)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [90]:
# slicing matrices
# slice columns

print(D)
D[:,0]

[[  4  12  24]
 [ 40  60  84]
 [112 144 180]]


array([  4,  40, 112])

In [91]:
# slice rows

D[0,:]

array([ 4, 12, 24])

# Vectors

##### A column vector or column matrix is an m × 1 matrix, that is, a matrix consisting of a single column of m elements,
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/32bf4d54c8e316178fca0b9f4a79dd0a0a34f34f?raw=true)
##### Similarly, a row vector or row matrix is a 1 × m matrix, that is, a matrix consisting of a single row of m elements,
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/507111acf945f5fe57c45ecc563ec02a4aff4a1b?raw=true)

https://www.wikiwand.com/en/Row_and_column_vectors

In [92]:
# Define vector 'x'

x = np.array([[2],[3],[1]])
print(x)
print()
print("Shape of the vector is:", x.shape)

[[2]
 [3]
 [1]]

Shape of the vector is: (3, 1)


In [93]:
# slicing elements of a vector.

x[1]

array([3])

In [94]:
# Operations with vectors:

print(x + x)
print()
print(x * x)
print()
print(x ** 2)

[[4]
 [6]
 [2]]

[[4]
 [9]
 [1]]

[[4]
 [9]
 [1]]


In [95]:
# https://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.ndarray.html

In [96]:
# Vector matrix multiplication:
print(A)
print(x.dot(A))

#here we can see the error of multiplication, we have the rules when performing vector matrix multiplication ... 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [97]:
print(x.T.dot(A))

[[21 27 33]]


In [98]:
# Element-wise Multiplication

print(np.multiply(A, x))
print()
print(np.multiply(x, A))

[[ 2  4  6]
 [12 15 18]
 [ 7  8  9]]

[[ 2  4  6]
 [12 15 18]
 [ 7  8  9]]


# Defining Tensors and perfom operations
### A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

In [99]:
# https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

In [100]:
# Tensor defining:

T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


Tensor Addition:

```python
     a111, a121, a131     a112, a122, a132
A = (a211, a221, a231),  (a112, a122, a132)

     b111, b121, t131     b112, b122, b132
B = (b211, t221, t231),  (b112, b122, b132)


C = A + B

     a111 + b111, a121 + b121, a131 + b131     a112 + b112, a122 + b122, a132 + b132
C = (a211 + b211, a221 + b221, a231 + b231),  (a112 + b112, a122 + b122, a132 + b132)
```

In [101]:
t_A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],])
t_B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
t_C = t_A + t_B
print(t_C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [102]:
# Tensor substraction, division and element-wise multiplication is like the addition elements operation:

t_C = t_A - t_B
print(t_C)

print()
t_C = t_A * t_B
print(t_C)

print()
t_C = t_A / t_B
print(t_C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [103]:
# Tensor Dot_product

t_C = np.tensordot(t_A, t_B, axes=0)
print(t_C[1])

[[[[[ 11  22  33]
    [ 44  55  66]
    [ 77  88  99]]

   [[121 132 143]
    [154 165 176]
    [187 198 209]]

   [[231 242 253]
    [264 275 286]
    [297 308 319]]]


  [[[ 12  24  36]
    [ 48  60  72]
    [ 84  96 108]]

   [[132 144 156]
    [168 180 192]
    [204 216 228]]

   [[252 264 276]
    [288 300 312]
    [324 336 348]]]


  [[[ 13  26  39]
    [ 52  65  78]
    [ 91 104 117]]

   [[143 156 169]
    [182 195 208]
    [221 234 247]]

   [[273 286 299]
    [312 325 338]
    [351 364 377]]]]



 [[[[ 14  28  42]
    [ 56  70  84]
    [ 98 112 126]]

   [[154 168 182]
    [196 210 224]
    [238 252 266]]

   [[294 308 322]
    [336 350 364]
    [378 392 406]]]


  [[[ 15  30  45]
    [ 60  75  90]
    [105 120 135]]

   [[165 180 195]
    [210 225 240]
    [255 270 285]]

   [[315 330 345]
    [360 375 390]
    [405 420 435]]]


  [[[ 16  32  48]
    [ 64  80  96]
    [112 128 144]]

   [[176 192 208]
    [224 240 256]
    [272 288 304]]

   [[336 352 368]
    [384 400 416]


# Example solving linear equations using vector and matrices

### We now have enough linear algebra notation to write a system of linear equations: Ax = b
* A is a matrix
* x is a vector
* b is a vector

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.solve.html

In [104]:
# Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

A = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A, b)

In [105]:
x

array([2., 3.])

In [106]:
# Check that the solution is correct:

np.allclose(np.dot(A, x), b)

True

# Q&A