# Providing info for numpy and show why is required.


In [2]:
import pandas as pd
import numpy as np

In [3]:
# read in the csv file aka dataframe creation

url_data = "https://raw.githubusercontent.com/sb0709/bootcamp_KSU/master/Data/data.csv"
data = pd.read_csv(url_data,sep=',')

Sources used to build the tutorial:

* A Primer on Scientific Programming with Python by Hans Petter Langtangen.
* Deep Learning by Ian Goodfellow, Yoshua Bengio, and Aaron Courville.
* https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
* https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/
* https://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.ndarray.html



##### This part does assume that the audience have previous experience with basic Linear Algebra, including Vectors, Matrices, Tensors.

### Scalars
##### The default data type in NumPy is float_

Source doc: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.scalars.html 

In [4]:
#listing the 

np.ScalarType

(int,
 float,
 complex,
 int,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.int8,
 numpy.uint8,
 numpy.int16,
 numpy.uint16,
 numpy.int32,
 numpy.uint32,
 numpy.int64,
 numpy.uint64,
 numpy.int64,
 numpy.uint64,
 numpy.float16,
 numpy.float32,
 numpy.float64,
 numpy.float128,
 numpy.complex64,
 numpy.complex128,
 numpy.complex256,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.void,
 numpy.datetime64,
 numpy.timedelta64)

In [5]:
a = np.array(3.1)

In [12]:
a

array(3.1)

# Defining Matrics and Vectors

##### A matrix  is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns:
![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Matrix.svg/494px-Matrix.svg.png?raw=true)

https://www.wikiwand.com/en/Matrix_(mathematics)

In [23]:
# Define matrix "A"

A = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(A)
print()
print("Shape of the matrix is:", A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of the matrix is: (3, 3)


### Addition, scalar multiplication and transposition

![alt text](https://github.com/sb0709/bootcamp_KSU/blob/master/pictures/matrix_table.png?raw=true)


https://www.wikiwand.com/en/Matrix_(mathematics)

In [33]:
B = A**2
print(B)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [34]:
C = A + B
print(C)

[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


In [39]:
# scalar multiply matrix 

D = 2 * C
D

array([[  4,  12,  24],
       [ 40,  60,  84],
       [112, 144, 180]])

In [36]:
# Transpose 
print(A.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [38]:
# inverse

print(np.linalg.inv(D))

# here we have also the Generalized inverse option to can calculate.

[[ 0.75       -0.75        0.25      ]
 [-1.27777778  1.13888889 -0.36111111]
 [ 0.55555556 -0.44444444  0.13888889]]


In [41]:
# Determinant

print(np.linalg.det(A))

6.66133814775094e-16


In [47]:
# Eigenvalues and Eigenvectors

eigvals, eigvecs = np.linalg.eig(A)

print(eigvals)
print()
print(eigvecs)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Vectors

##### A column vector or column matrix is an m × 1 matrix, that is, a matrix consisting of a single column of m elements,
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/32bf4d54c8e316178fca0b9f4a79dd0a0a34f34f?raw=true)
##### Similarly, a row vector or row matrix is a 1 × m matrix, that is, a matrix consisting of a single row of m elements,
![alt text](https://wikimedia.org/api/rest_v1/media/math/render/svg/507111acf945f5fe57c45ecc563ec02a4aff4a1b?raw=true)

https://www.wikiwand.com/en/Row_and_column_vectors

In [56]:
# Define vector 'x'

x = np.array([[2],[3],[1]])
print(x)
print()
print("Shape of the vector is:", x.shape)

[[2]
 [3]
 [1]]

Shape of the vector is: (3, 1)


In [58]:
# Operations with vectors:

print(x + x)
print()
print(x * x)
print()
print(x ** 2)

[[4]
 [6]
 [2]]

[[4]
 [9]
 [1]]

[[4]
 [9]
 [1]]


In [59]:
# https://docs.scipy.org/doc/numpy-1.10.0/reference/arrays.ndarray.html

In [66]:
# Vector matrix multiplication:
print(A)
print(x.dot(A))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [67]:
print(x.T.dot(A))

[[21 27 33]]


In [70]:
# Element-wise Multiplication

print(np.multiply(A, x))
print()
print(np.multiply(x, A))

[[ 2  4  6]
 [12 15 18]
 [ 7  8  9]]

[[ 2  4  6]
 [12 15 18]
 [ 7  8  9]]


# Defining Tensors and perfom operations
### A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.

In [71]:
# https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/